### ISSUE TITLE
有报错大佬，我需要的模块都安装了最后还报模块不存在

### ISSUE THREAD

**Issue by liushuai05** [icezerowjj/Shanghai-Au-Futures#1]
Traceback (most recent call last):
  File "./Project_AU.py", line 13, in <module>
    import statsmodels.api as sm
  File "/usr/lib/python2.7/site-packages/statsmodels/api.py", line 5, in <module>
    from . import iolib
  File "/usr/lib/python2.7/site-packages/statsmodels/iolib/__init__.py", line 1, in <module>
    from .foreign import StataReader, genfromdta, savetxt
  File "/usr/lib/python2.7/site-packages/statsmodels/iolib/foreign.py", line 14, in <module>
    from statsmodels.compat.python import (lzip, lmap, lrange,
  File "/usr/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/usr/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 11, in <module>
    from statsmodels.tools.validation import array_like
  File "/usr/lib/python2.7/site-packages/statsmodels/tools/validation/__init__.py", line 1, in <module>
    from .validation import (array_like, bool_like,  dict_like,
  File "/usr/lib/python2.7/site-packages/statsmodels/tools/validation/validation.py", line 1, in <module>
    from collections.abc import Mapping
ImportError: No module named abc

**Comment by icezerowjj** [comment]
你好，这个project太老了，是用 2.7做的。建议你找到3.5及以上Python相关的package再试试。而且module not found error跟环境配置有很大关系，肯恩需要多搜索一下花点时间去调配。但是Python2确实应该被淘汰了个人感觉
